package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 16 21:37:08 PDT 2015
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void populateMovieData();

    void populateMovieData(String month);
}
