package model.client;

import model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 16 21:37:08 PDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void populateMovieData() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateMovieData",null,null);
        return;
    }

    public void populateMovieData(String month) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateMovieData",new String [] {"java.lang.String"},new Object[] {month});
        return;
    }
}
